#!/usr/bin/python

import pwn
pwn.context.update(arch="amd64")
code = pwn.asm("""
add rdi, 0x331337
""" )
process = pwn.process("/challenge/run")
process.write(code)
print(process.readall())

pwn.college{UIOCxEe9eq7NG86x5jM-qoJYWoz.0VN5EDL1gjM1QzW}
