#!/usr/bin/python
import pwn
pwn.context.update(arch="amd64")
code = pwn.asm("""
imul rdi, rsi
add rdi, rdx
mov rax, rdi
""" )
process = pwn.process("/challenge/run")
process.write(code)
print(process.readall())

pwn.college{EjnkU1pDtr2mH28XQmYF3j8rhkS.0lN5EDL1gjM1QzW}
