#!/usr/bin/python
import pwn
pwn.context.update(arch="amd64")
code = pwn.asm("""
mov rax, 0x1337
mov r12, 0xCAFED00D1337BEEF
mov rsp, 0x31337
""" )
process = pwn.process("/challenge/run")
process.write(code)
print(process.readall())




pwn.college{clgxd-maeq4v8EPobVs_gFFNE1j.dBTM4MDL1gjM1QzW}
