#!/usr/bin/python
import pwn
pwn.context.update(arch="amd64")
code = pwn.asm("""
mov rax, rdi
div rsi
""" )
process = pwn.process("/challenge/run")
process.write(code)
print(process.readall())


pwn.college{gr0ORXDkY4qTIKlu4fBDW0wx84K.01N5EDL1gjM1QzW}
