#!/usr/bin/python
import pwn
pwn.context.update(arch="amd64")
code = pwn.asm("""
mov rdi, 0x1337
""" )
process = pwn.process("/challenge/run")
process.write(code)
print(process.readall())


pwn.college{wReU_MFticV8ZFzKgrpdiANw-F9.0FN5EDL1gjM1QzW}
